### ISSUE TITLE
output selection ui in buffer-parser is broken from node-red@2.1.3 and newer

### ISSUE THREAD

**Issue by muradnik** [Steve-Mcl/node-red-contrib-buffer-parser#11]
Just notifying so you can check it out.

When trying to change the output format in buffer-parser some change in node-red editor prevents the option menu from working correctly.

![buffer-parser](https://user-images.githubusercontent.com/73789362/147081881-4a018fa8-cd76-481a-b8a2-10a144312eb5.jpg)

This is working just fine in earlier version of node-red@2.1.2 and earlier.

When manually changing the text of the output field to keyvalue, object, array, ... output of buffer-parser node is working correctly.

So I'm gessing this is some sort of js / css issue.

node-red@2.1.4-1
nodejs@14.18.2
node-red-contrib-buffer-parser@3.1.7

**Comment by Steve-Mcl** [comment]
That is odd. I'll check it over. Thanks for reporting it.

**Comment by muradnik** [comment]
<details><summary>Versions:</summary>

- node-red@2.1.4-1
- nodejs@14.18.2
- node-red-contrib-buffer-parser@3.2.0

</details>

Hi @Steve-Mcl, it seems that UI problem is resolved in latest version (v3.2.0) of this node.
Thanks 👍
