### ISSUE TITLE
When adding a bool UI specification, increment the offset instead of bit past 8

### ISSUE THREAD

**Issue by nagisa** [Steve-Mcl/node-red-contrib-buffer-parser#23]
When incrementally adding rows to the UI specification, the node configuration helpfully increments the byte or bit offset based on the last row when adding rows.

When the last row is a "bool" and its bit offset is 7, adding a new row will preset the bit offset at 8, which cannot possibly be a valid bit offset in a byte from a buffer.

I suggest that when the bit offset reaches 8 in this case, the byte offset should be incremented by one and the bit offset set to 0.

(Of course this will depend on length, so if length is not 1, then a multiple of length should be considered here)

**Comment by Steve-Mcl** [comment]
> which cannot possibly be a valid bit offset in a byte from a buffer.

Except it is. It will automatically access the next byte and so forth. Give it a go and see. 

This was a deliberate design choice to simplify things like 16-bit access. 

If you want to you can access a bit 128 (assuming there are enough bytes in the buffer)

**Comment by nagisa** [comment]
Ah, I see. Seems like I made incorrect assumptions and spent way more time fiddling with indices than I strictly needed to ^^

**Comment by Steve-Mcl** [comment]
> spent way more time fiddling with indices than I strictly needed to

Exactly this ☝️ 😂
