### ISSUE TITLE
Feature Request: support of signed integers

### ISSUE THREAD

**Issue by ramtorio** [Steve-Mcl/node-red-contrib-buffer-parser#24]
I recently came across the difference between signed and unsinged integers and twos complement. To be more specific, I suddenly got a Temperature reading several 10k degrees too hot because I apparently forgot that the data source supplies it's temperature reading as sint16, but silly me thought that it wouldn't matter and used the unit16 type... Which worked until the outside temperatures dropped below zero. 

I'm currently trying to wrap my head around the concept to build an alternative, but it would of course be much simpler if the buffer parser could do this on its own.

Do you think it would be possible to add sint as supported data type?

**Comment by Steve-Mcl** [comment]
The buffer parser already supports signed integers (int16, int32, etc)

Perhaps if you provide a reproducible flow (using injects to simulate data) and include your expectations I might better understand.

**Comment by Steve-Mcl** [comment]
Closing this for now. Please feel free to reopen this if you have further questions or wish to respond to my previous comment.
