### ISSUE TITLE
Keep incoming values

### ISSUE THREAD

**Issue by SindreLindahl** [Steve-Mcl/node-red-contrib-buffer-parser#25]
Looks like everything from incoming msg is lost in output msg(s)? Would it be possible to keep all other data not used by the node itself, and send it to output? Otherwise all continuity is lost before/after buffer-parser node.

**Comment by Steve-Mcl** [comment]
This only occurs when you output multiple. This is to avoid unnecessary/expensive cloning. 

There are ways around this - see: https://discourse.nodered.org/t/buffer-parser-node-drops-all-incoming-data/93892/10?u=steve-mcl

In the meantime, I will consider adding this as an optional feature (disabled by default)

**Comment by SindreLindahl** [comment]
Thx, that solves it.
