### ISSUE TITLE
Interface issue with fanned output

### ISSUE THREAD

**Issue by mikeS7** [Steve-Mcl/node-red-contrib-buffer-parser#6]
Hi Steve,

there are unexpected number of outputs when fan out is not selected. Steps to reproduce:

1. Add node to workspace and add several items. Do not check fan out.
2. Press Done.
3. Open edit dialog for node again and press Cancel.
4. Select node on workspace.

Check number on node outputs.

Visual record can be found in the forum [https://discourse.nodered.org/t/updated-node-red-contrib-buffer-parser-v3-1-1/25879/45?u=mikes7](https://discourse.nodered.org/t/updated-node-red-contrib-buffer-parser-v3-1-1/25879/45?u=mikes7)

**Comment by Steve-Mcl** [comment]
Hi Mike, I think I have this one rather odd issue solved. Just waiting on some feedback from Dave C on something else and I will release.  Probably later this evening.

How are you liking the latest additions?

As always, thanks for taking the time to report issues.

**Comment by Steve-Mcl** [comment]
Fixed in V3.1.2
Thanks.
